export const SUBMIT_CONTACT_MESSAGE = 'SUBMIT_CONTACT_MESSAGE';
export const SUBMIT_CONTACT_MESSAGE_SUCCESS = 'SUBMIT_CONTACT_MESSAGE_SUCCESS';
export const SUBMIT_CONTACT_MESSAGE_FAILURE = 'SUBMIT_CONTACT_MESSAGE_FAILURE';
