export const FETCH_FACEBOOK_POSTS = 'FETCH_FACEBOOK_POSTS';
export const FETCH_FACEBOOK_POSTS_SUCCESS = 'FETCH_FACEBOOK_POSTS_SUCCESS';
export const FETCH_FACEBOOK_POSTS_FAILURE = 'FETCH_FACEBOOK_POSTS_FAILURE';
